export const DASHBOARD = '/'
export const IURAN = '/iuran'
export const DATA_WARGA = '/data-warga'
export const PENGELUARAN_KAS = '/pengeluaran-kas'
export const LAPORAN_KEUANGAN = '/laporan-keuangan'